module.exports = {
  backupWallet: 'backupwallet', // namecoin
  BuildMerkleTree: 'buildmerkletree', // namecoin
  getAccount: 'getaccount', // namecoin
  getAccountAddress: 'getaccountaddress', // namecoin
  getAddressesByAccount: 'getaddressesbyaccount', // namecoin
  getAddressesByAccount: 'getaddressesbyaccount', // namecoin
  getAuxBlock: 'getauxblock', // namecoin
  getBalance: 'getbalance', // namecoin
  getBlockByCount: 'getblockbycount', // namecoin
  getBlockCount: 'getblockcount', // namecoin
  getBlockByHash: 'getblockbyhash', // namecoin
  getBlockNumber: 'getblocknumber', // namecoin
  getConnectionCount: 'getconnectioncount', // namecoin
  getDifficulty: 'getdifficulty', // namecoin
  getGenerate: 'getgenerate', // namecoin
  getHashesPerSec: 'gethashespersec', // namecoin
  getInfo: 'getinfo', // namecoin
  getNewAddress: 'getnewaddress', // namecoin
  getReceivedByAccount: 'getreceivedbyaccount', // namecoin
  getReceivedByAddress: 'getreceivedbyaddress', // namecoin
  getTransaction: 'gettransaction', // namecoin
  getWork: 'getwork', // namecoin
  getWorkAux: 'getworkaux', // namecoin
  help: 'help', // namecoin
  listAccounts: 'listaccounts', // namecoin
  listReceived: 'listReceived', // namecoin
  listReceivedByAccount: 'listreceivedbyaccount', // namecoin
  listReceivedByAddress: 'listreceivedbyaddress', // namecoin
  listTransactions: 'listtransactions', // namecoin
  move: 'movecmd', // namecoin
  sendFrom: 'sendfrom', // namecoin
  sendMany: 'sendmany', // namecoin
  sendToAddress: 'sendtoaddress', // namecoin
  setAccount: 'setaccount', // namecoin
  setGenerate: 'setgenerate', // namecoin
  setTxFee: 'settxfee', // namecoin
  stop: 'stop', // namecoin
  validateAddress: 'validateaddress' // namecoin
};
